title           = "#todayilearned"
baseURL         = "https://todayilearned.jm3.net/"
googleAnalytics = "UA-228926-19"
languageCode    = "en-us"

theme = "rocker-panel"
#theme = "rocker-panel-clone-symlink"

[params]
excludedTypes    = ["page"] # Content types excluded from recent posts + archives page
featherIconsCDN  = true
font             = "Rubik" # should match the name of a Google Font
recentPostsCount = 10
primaryType      = "learnings"

subtitle = "John Manoogian (jm3)"
headline = "Daily updates as I fast-forward merge* my web skills up to 2019 levels"
copyright = "<i class='icon copyleft'></i> copyleft 2020 &middot; John Manoogian III (jm3) &middot; all rights reserved, all wrongs reversed, no punches pulled [*](https://ariya.io/2013/09/fast-forward-git-merge)"
css = [
  "css/normalize.css",
  "css/colors.css",
  "css/grid.css",
  # "css/syntax-highlighting.css",
  # "css/typography.css"
  # "css/orig.css",
]

# weight: basically = ordering
# pre: feather icon name
[[menu.main]]
name = "Home"
url = "/"
pre = "home"
weight = 1

[[menu.main]]
name = "Learnings"
url = "/learnings"
pre = "sun"
weight = 2

[[menu.main]]
url = "/projects/"
pre = "box"
name = "Projects"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
pre = "tag"
weight = 4

[[menu.main]]
name = "About"
url = "/about"
pre = "info"
weight = 5

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/jm3"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/nerdshitposting"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
tag = "tags"
