baseURL = "https://todayilearned.jm3.net/"
languageCode = "en-us"
title = "#todayilearned"
theme = "rocker-panel"
#theme = "rocker-panel-clone-symlink"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-228926-19"

[params]
	excludedTypes = ["page"] # Content types excluded from recent posts + archives page
	featherIconsCDN = true
  font = "Rubik" # should match the name of a Google Font
	recentPostsCount = 10
  primaryType = "learnings"
  subtitle = "Daily updates as I [fast-forward merge](https://ariya.io/2013/09/fast-forward-git-merge) my web skills up to 2019 levels"
  copyright = "© ← copyleft <abbr title='John Manoogian III'>jm3</abbr> &mdash; all rights reserved, all wrongs reversed, no punches pulled"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Learnings"
url = "/learnings"
weight = 2

[[menu.main]]
url = "/projects/"
name = "Projects"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[menu.main]]
name = "About"
url = "/about"
weight = 5

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/jm3"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/jm3"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
tag = "tags"
